curl -X DELETE -s localhost:9200/workflows
curl -X DELETE -s localhost:9200/rereco_requests
curl -X DELETE -s localhost:9200/requests
curl -X DELETE -s localhost:9200/chained_requests
curl -X DELETE -s localhost:9200/campaigns
curl -X DELETE -s localhost:9200/chained_campaigns
curl -X DELETE -s localhost:9200/flows
curl -X DELETE -s localhost:9200/last_sequences
curl -X DELETE -s localhost:9200/tags
curl -X DELETE -s localhost:9200/processing_strings
